export const ASYNC_USER_TOKEN_KEY = "@user_token"
export const ASYNC_PRODUCTS_ARRAY_KEY = "@products_array"
export const ASYNC_USER_CURRENTUSER_KEY = "@user_currentUser"
export const ASYNC_MEDIA_WATERMARK_PHOTOS_KEY = "@media_watermarkPhotos"
export const ASYNC_MEDIA_WATERMARK_VIDEOS_KEY = "@media_watermarkVideos"
export const EXPO_CONSTANTS_INSTALLATION_ID = "EXPO_CONSTANTS_INSTALLATION_ID"