export const CLEAR_USER_DATA = "CLEAR_USER_DATA";
export const ENABLE_FORCE_LOGOUT = "ENABLE_FORCE_LOGOUT";
export const DISABLE_FORCE_LOGOUT = "DISABLE_FORCE_LOGOUT";
export const USER_POSTS_STATE_CHANGE = "USER_POSTS_STATE_CHANGE";
export const USER_FOLLOWING_STATE_CHANGE = "USER_FOLLOWING_STATE_CHANGE";

export const USER_STATE_CHANGE = "USER_STATE_CHANGE";
export const USER_TOKEN_STATE_CHANGE = "USER_TOKEN_STATE_CHANGE";
export const USER_PROFILE_LOCK_STATE_CHANGE = "USER_PROFILE_LOCK_STATE_CHANGE";
export const USER_PROFILE_LOCK_TIMEOUT_STATE_CHANGE = "USER_PROFILE_LOCK_TIMEOUT_STATE_CHANGE";
export const USER_PROFILE_PIN_STATE_CHANGE = "USER_PROFILE_PIN_STATE_CHANGE";

export const USER_CART_STATE_CHANGE = "USER_CART_STATE_CHANGE";
export const USER_CART_ITEM_STATE_CHANGE = "USER_CART_ITEM_STATE_CHANGE";
export const USER_CART_STATE_ERROR = "USER_CART_STATE_ERROR";
export const USER_AUTH_DATA_STATE_CHANGE = "USER_AUTH_DATA_STATE_CHANGE";
export const USER_AUTH_ERROR_STATE_CHANGE = "USER_AUTH_ERROR_STATE_CHANGE";
export const USER_UPDATE_STATE_CHANGE = "USER_UPDATE_STATE_CHANGE";
export const USER_BANKS_STATE_CHANGE = "USER_BANKS_STATE_CHANGE";
export const USER_HPV_STATE_CHANGE = "USER_HPV_STATE_CHANGE";
export const USER_POINTS_STATE_CHANGE = "USER_POINTS_STATE_CHANGE";
export const USER_SYARAT_ROOT_STATE_CHANGE = "USER_SYARAT_ROOT_STATE_CHANGE";
export const USER_SALDO_STATE_CHANGE = "USER_SALDO_STATE_CHANGE";

export const USER_LOGIN_TOKEN_STATE_CHANGE = "USER_LOGIN_TOKEN_STATE_CHANGE";
export const USER_REGISTER_TOKEN_STATE_CHANGE =
  "USER_REGISTER_TOKEN_STATE_CHANGE";
export const USER_AUTH_DELETE_STATE_CHANGE = "USER_AUTH_DELETE_STATE_CHANGE";

export const USER_ADDRESS_STATE_CHANGE = "USER_ADDRESS_STATE_CHANGE";
export const USER_ADDRESS_STATE_CLEAR = "USER_ADDRESS_STATE_CLEAR";
export const USER_ADDRESS_UPDATE_STATE_CHANGE =
  "USER_ADDRESS_UPDATE_STATE_CHANGE";

export const USER_MASTERKURIR_STATE_CHANGE = "USER_MASTERKURIR_STATE_CHANGE";
export const USER_RAJAONGKIR_STATE_CHANGE = "USER_RAJAONGKIR_STATE_CHANGE";
export const USER_COURIERS_STATE_CHANGE = "USER_COURIERS_STATE_CHANGE";

export const USER_CHECKOUT_STATE_CHANGE = "USER_CHECKOUT_STATE_CHANGE";
export const USER_OTP_STATE_CHANGE = "USER_OTP_STATE_CHANGE";
export const USER_OTP_VALIDATION_STATE_CHANGE =
  "USER_OTP_VALIDATION_STATE_CHANGE";

export const CLEAR_PRODUCT_DATA = "CLEAR_PRODUCT_DATA";
export const PRODUCTS_DATA_STATE_CHANGE = "PRODUCTS_DATA_STATE_CHANGE";
export const PRODUCT_ITEM_DATA_STATE_CHANGE = "PRODUCT_ITEM_DATA_STATE_CHANGE";
export const PRODUCT_MAX_INDEX_STATE_CHANGE = "PRODUCT_MAX_INDEX_STATE_CHANGE";
export const PRODUCT_SEARCH_FILTER_STATE_CHANGE = "PRODUCT_SEARCH_FILTER_STATE_CHANGE";
export const MAXIMUM_ITEM_PER_PRODUCT = 20;

export const HISTORY_CHECKOUT_STATE_CHANGE = "HISTORY_CHECKOUT_STATE_CHANGE";
export const HISTORY_DELIVERY_STATE_CHANGE = "HISTORY_DELIVERY_STATE_CHANGE";
export const HISTORY_DELIVERY_STATUS_STATE_CHANGE =
  "HISTORY_DELIVERY_STATUS_STATE_CHANGE";
export const HISTORY_DASHBOARD_STATE_CHANGE = "HISTORY_DASHBOARD_STATE_CHANGE";

export const HISTORY_CHECKOUTS_STATE_CHANGE = "HISTORY_CHECKOUTS_STATE_CHANGE";
export const HISTORY_DELIVERIES_STATE_CHANGE =
  "HISTORY_DELIVERIES_STATE_CHANGE";
export const HISTORY_CLEAR_DATA = "HISTORY_CLEAR_DATA";

export const BLOG_STATE_CHANGE = "BLOG_STATE_CHANGE";
export const BLOG_STATE_INCREMENT_CHANGE = "BLOG_STATE_INCREMENT_CHANGE";
export const BLOG_PAGE_NUMBER_STATE_CHANGE = "BLOG_PAGE_NUMBER_STATE_CHANGE";
export const BLOG_ITEM_STATE_CHANGE = "BLOG_ITEM_STATE_CHANGE";
export const BLOG_CLEAR_DATA = "BLOG_CLEAR_DATA";

export const HOME_SLIDER_STATE_CHANGE = "HOME_SLIDER_STATE_CHANGE";
export const HOME_BANNER_STATE_CHANGE = "HOME_BANNER_STATE_CHANGE";
export const HOME_CLEAR_DATA = "HOME_CLEAR_DATA";

export const PROFILE_MEDIAKIT_CHANGE = "PROFILE_MEDIAKIT_CHANGE";
export const PROFILE_TNC_CHANGE = "PROFILE_TNC_CHANGE";
export const PROFILE_PRIVACY_CHANGE = "PROFILE_PRIVACY_CHANGE";
export const PROFILE_FAQ_CHANGE = "PROFILE_FAQ_CHANGE";
export const PROFILE_CLEAR_DATA = "PROFILE_CLEAR_DATA";

export const MEDIA_KIT_WATERMARK_DATA_STATE_CHANGE = "MEDIA_KIT_WATERMARK_DATA_STATE_CHANGE";
export const MEDIA_KIT_PHOTOS_STATE_CHANGE = "MEDIA_KIT_PHOTOS_STATE_CHANGE";
export const MEDIA_KIT_PHOTOS_URI_STATE_CHANGE = "MEDIA_KIT_PHOTOS_URI_STATE_CHANGE";
export const MEDIA_KIT_PHOTOS_ERROR_STATE_CHANGE = "MEDIA_KIT_PHOTOS_ERROR_STATE_CHANGE";
export const MEDIA_KIT_VIDEOS_STATE_CHANGE = "MEDIA_KIT_VIDEOS_STATE_CHANGE";
export const MEDIA_KIT_FONTS_STATE_CHANGE = "MEDIA_KIT_FONTS_STATE_CHANGE";
export const MEDIA_KIT_COLORS_STATE_CHANGE = "MEDIA_KIT_COLORS_STATE_CHANGE";
export const MEDIA_KIT_SIZES_STATE_CHANGE = "MEDIA_KIT_SIZES_STATE_CHANGE";
export const MEDIA_KIT_CLEAR_DATA = "MEDIA_KIT_CLEAR_DATA";

export const MEDIA_PROFILE_PICTURE_STATE_CHANGE =
  "MEDIA_PROFILE_PICTURE_STATE_CHANGE";
export const MEDIA_WATERMARK_LAYOUT_STATE_CHANGE = "MEDIA_WATERMARK_LAYOUT_STATE_CHANGE";
export const MEDIA_WATERMARK_VIDEOS_STATE_CHANGE = "MEDIA_WATERMARK_VIDEOS_STATE_CHANGE";
export const MEDIA_WATERMARK_VIDEOS_OVERWRITE = "MEDIA_WATERMARK_VIDEOS_OVERWRITE";
export const MEDIA_CLEAR_DATA = "MEDIA_CLEAR_DATA";
export const MEDIA_DOWNLOAD_STATE_CHANGE = "MEDIA_DOWNLOAD_STATE_CHANGE";

export const DELIVERY_MANIFEST_HEADER = [
  {
    manifest_code: null,
    manifest_description: "Pesanan diproses",
    manifest_date: null,
    manifest_time: null,
    city_name: "BANDUNG",
  },
  {
    manifest_code: null,
    manifest_description: "Pesanan dijemput oleh kurir",
    manifest_date: null,
    manifest_time: null,
    city_name: "BANDUNG",
  },
];
